name: Lint Splinter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint_gameroom_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint Gameroom Client
        run : sleep 5
        # run: docker-compose -f docker/compose/run-lint.yaml up --abort-on-container-exit lint-gameroom-client

  lint_splinter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint Splinter
        run : sleep 5
        # run: docker-compose -f docker/compose/run-lint.yaml up --abort-on-container-exit lint-splinter

  run_clippy_on_splinter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Clippy on Splinter
        run : sleep 5
        # run: docker-compose -f docker/compose/run-lint.yaml up --abort-on-container-exit clippy-splinter
